version: "3.7"
services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672

    con:
        build: consumer
        links:
            - rabbitmq
        command: python consumer.py

    prod:
        build: producer
        links:
            - rabbitmq
        command: python producer.py